testvars_fast:
  reportfilename: "nlc_results.csv"
  from_date: "2023-07-27 00:00:00"
  to_date: "2024-08-27 00:00:00"
  csv_file: "/home/jw/src/cbot/data/BTC_USD_OHLC_60_20230727_20240827.csv"
  rolling_window_size: 16   #! this is also the lookback period
  max_loops: 100000000  #! unlimited by default.  Set to 100 for short testing
  negRange: [0.1, 4.0, 0.1]
  limRange: [0.0, 2.0, 0.1]
  conRange: [1.0, 5.0, 0.1]
